# Generated by Django 4.2.5 on 2023-10-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
